# Generated by Django 2.2.12 on 2020-05-02 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(null=True)),
                ('sponsorDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(blank=True, default='name', max_length=50)),
                ('netID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('interests', models.CharField(blank=True, default='interests', max_length=100)),
                ('gradYear', models.IntegerField(default=0)),
                ('courseWork', models.CharField(blank=True, default='course', max_length=500)),
                ('projects', models.CharField(blank=True, default='projects', max_length=500)),
                ('experiences', models.CharField(blank=True, default='experiences', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('members', models.ManyToManyField(to='resume_book.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiterName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRating', models.FloatField(null=True)),
                ('projectDescription', models.CharField(max_length=500)),
                ('companyReview', models.CharField(max_length=500)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Company')),
                ('netID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Student')),
            ],
        ),
    ]
