# Generated by Django 2.2.11 on 2020-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('netID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('resumeID', models.IntegerField(null=True)),
                ('interests', models.CharField(max_length=100)),
            ],
        ),
    ]
