# Generated by Django 2.2.11 on 2020-04-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
