# Generated by Django 2.2.12 on 2020-04-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0002_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField(null=True)),
                ('sponsorDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradYear', models.IntegerField(null=True)),
                ('courseWork', models.CharField(max_length=500)),
                ('projects', models.CharField(max_length=500)),
                ('experiences', models.CharField(max_length=500)),
                ('netID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumeNetID', to='resume_book.Student')),
                ('resumeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumeResumeID', to='resume_book.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiterName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRating', models.IntegerField(null=True)),
                ('projectDescription', models.CharField(max_length=500)),
                ('companyReview', models.CharField(max_length=500)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Company')),
                ('netID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_book.Student')),
            ],
        ),
    ]
