# Generated by Django 2.2.5 on 2020-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0003_company_internship_recruiter_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='dateAdded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
