# Generated by Django 2.2.5 on 2020-04-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0004_resume_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
