# Generated by Django 2.2.5 on 2020-04-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0006_auto_20200408_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='numberRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courseWork',
            field=models.CharField(blank=True, default='course', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='experiences',
            field=models.CharField(blank=True, default='experiences', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='gradYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.CharField(blank=True, default='interests', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects',
            field=models.CharField(blank=True, default='projects', max_length=500),
        ),
    ]
