# Generated by Django 2.2.11 on 2020-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0007_auto_20200409_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='members',
            field=models.ManyToManyField(to='resume_book.Student'),
        ),
    ]
