# Generated by Django 2.2.11 on 2020-04-10 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_book', '0008_studentgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sponsorDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='internship',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='internship',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
